In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_excel('Spam Data.xlsx', names = ['labels', 'messages'])

In [3]:
df.head()

labels                                           messages
0    ham                      Ok lar... Joking wif u oni...
1   spam  Free entry in 2 a wkly comp to win FA Cup fina...
2    ham  U dun say so early hor... U c already then say...
3    ham  Nah I don't think he goes to usf, he lives aro...
4   spam  FreeMsg Hey there darling it's been 3 week's n...

In [4]:
df.shape

(5571, 2)

In [5]:
import re
import nltk

In [6]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Yogesh\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [7]:
from nltk.stem import WordNetLemmatizer
lemma = WordNetLemmatizer()

In [8]:
from nltk.corpus import stopwords

In [9]:
corpus = []

In [10]:
for i in range(0, len(df)):
    words = re.sub('[^a-zA-Z]', ' ', str(df['messages'][i]))
    words = words.lower()
    words = words.split()
    words = [lemma.lemmatize(word) for word in words if word not in set(stopwords.words('english'))]
    
    words = ' '.join(words)
    
    corpus.append(words)

In [11]:
len(corpus)

5571

In [12]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000)
X = cv.fit_transform(corpus).toarray()

In [13]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [14]:
X.shape

(5571, 5000)

In [20]:
y = pd.get_dummies(df['labels'])

In [22]:
y = y.iloc[:,1].values

In [23]:
y

array([0, 1, 0, ..., 0, 0, 0], dtype=uint8)

In [27]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [30]:
xtrain.shape, ytrain.shape

((4456, 5000), (4456,))

In [31]:
from sklearn.naive_bayes import MultinomialNB

In [33]:
model = MultinomialNB().fit(xtrain, ytrain)

In [36]:
ypred = model.predict(xtest)

In [37]:
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(ytest, ypred))
print(accuracy_score(ytest, ypred))

[[955  10]
 [ 13 137]]
0.979372197309417


In [38]:
from sklearn.metrics import classification_report
print(classification_report(ytest, ypred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       965
           1       0.93      0.91      0.92       150

    accuracy                           0.98      1115
   macro avg       0.96      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115

